// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
)

type User struct {
	ID        int64          `json:"id"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Username  string         `json:"username"`
	Password  sql.NullString `json:"password"`
	Active    sql.NullBool   `json:"active"`
	Timezone  sql.NullString `json:"timezone"`
}
