# https://taskfile.dev

version: '3'

vars:
  PROJECT: "onpicket"

env:
  CGO_ENABLED: 1
dotenv:
  - .env

tasks:
  default:
    desc: Show all possible tasks
    cmds:
      - task --list-all
    silent: true

  dev:
    desc: Run the local development server; requires cosmtrek/air
    cmds:
      - air

  yarn:
    desc: Install javascript dependencies
    cmds:
      - yarn

  tailwind:
    desc: Install tailwind dependencies
    cmds:
      - yarn tailwind

  alpine:
    desc: Install Alpine.js dependencies
    cmds:
      - yarn alpine

  assets:
    desc: Run all javascript related tasks in one go
    cmds:
      - task: yarn
      - task: tailwind
      - task: alpine

  doc-up:
    desc: Run `docker compose up`
    summary: |
      This is used to test all components together, not for development.

      Use `task bootstrap && task dev` for local dev
    cmds:
      - docker compose up -d

  docker-build:
    desc: Build docker locally
    cmds:
      - docker build . -t {{.PROJECT}}

  docker-run:
    desc: Run the locally built container
    cmds:
      - docker run --rm -it {{.PROJECT}}

  codegen:
    desc: Run oapi-codegen
    cmds:
      - oapi-codegen --config=spec/cfg.yaml spec/oapi-spec.yaml

  bootstrap:
    desc: Bootstrap the dev environment without docker-compose
    cmds:
      - task: nats
      - task: mongo

  nats:
    desc: Run the local NATS box in detached mode
    cmds:
      - docker run --name {{.PROJECT}}-nats --rm -d -p 4222:4222 -p 8222:8222 nats --http_port 8222

  nats-box:
    desc: Run the interactive natsio/nats-box
    cmds:
      - docker run --name {{.PROJECT}}-nats-box --network host --rm -p 4222:4222 -p 8222:8222 -ti natsio/nats-box

  mongo:
    desc: Run a MongoDB instance locally
    cmds:
      - |
        docker run --rm -d \
        -e MONGO_INITDB_ROOT_USERNAME=root \
        -e MONGO_INITDB_ROOT_PASSWORD=root \
        -e MONGO_INITDB_DATABASE=admin \
        -p 27016:27017 \
        --name {{.PROJECT}}-mongo \
        -v onpicket_mongo:/data/db \
        mongo:latest
