openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "OnPicket API"
  description: ""
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://localhost:9898/api
paths:
  /healthz:
    get:
      summary: Healthcheck endpoint for the API
      operationId: healthz
      responses:
        '200':
          description: Health endpoint
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Healthz'
  /users:
    get:
      summary: Return all users
      operationId: listUsers
      responses:
        '200':
          description: User response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserBody'
      responses:
        '201':
          description: User response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '405':
          description: Method not found
        '400':
          description: Bad request

        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    User:
      required:
        - timezone
        - username
      properties:
        timezone:
          type: string
        username:
          type: string
    NewUser:
      required:
        - username
        - timezone
        - password1
        - password2
      properties:
        username:
          type: string
        timezone:
          type: string
        password1:
          type: string
        password2:
          type: string

    Error:
      type: object
      required:
        - code
        - status
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        status:
          type: string
          description: Error message
        body:
          type: object

    Healthz:
      type: object
      required:
        - status
        - version
      properties:
        status:
          type: string
        version:
          type: string
  requestBodies:
    UserBody:
      description: JSON of new user
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewUser'
