openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "OnPicket API"
  description: ""
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /healthz:
    get:
      summary: Healthcheck endpoint for the API
      operationId: healthz
      responses:
        '200':
          description: Health endpoint
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Healthz'
  /users:
    get:
      summary: Return all users
      operationId: listUsers
      responses:
        '200':
          description: User response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
#    default:
#      description: Unexpected error
#      content:
#        application/json:
#          schema:
#            $ref: '#/components/schemas/Error'


components:
  schemas:
    User:
      allOf:
        - $ref: '#/components/schemas/NewUser'
        - required:
          - id
          properties:
            id:
              type: integer
              format: int64
              description: Unqiue id of User
    NewUser:
      required:
        - name
      properties:
        username:
          type: string
        timezone:
          type: string
        password1:
          type: string
        password2:
          type: string

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    Healthz:
      required:
        - status
        - version
      properties:
        status:
          type: string
        version:
          type: string
