openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "OnPicket API"
  description: ""
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://localhost:9898/api
paths:
  /healthz:
    get:
      summary: Healthcheck endpoint for the API
      operationId: healthz
      responses:
        '200':
          description: Health endpoint
          headers:
            X-Ratelimit-Limit:
              $ref: '#/components/headers/X-Ratelimit-Limit'
            X-Ratelimit-Remaining:
              $ref: '#/components/headers/X-Ratelimit-Remaining'
            X-Ratelimit-Reset:
              $ref: '#/components/headers/X-Ratelimit-Reset'
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Healthz'
  /scans:
    get:
      summary: Return all scans
      operationId: listScans
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - $ref: '#/components/parameters/PageSortParam'
      responses:
        '200':
          description: Scan list response
          headers:
            X-Ratelimit-Limit:
              $ref: '#/components/headers/X-Ratelimit-Limit'
            X-Ratelimit-Remaining:
              $ref: '#/components/headers/X-Ratelimit-Remaining'
            X-Ratelimit-Reset:
              $ref: '#/components/headers/X-Ratelimit-Reset'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scan'
    post:
      summary: Create a new Scan
      operationId: createScan
      requestBody:
        $ref: '#/components/requestBodies/ScanBody'
      responses:
        '201':
          description: Scan response
          headers:
            X-Ratelimit-Limit:
              $ref: '#/components/headers/X-Ratelimit-Limit'
            X-Ratelimit-Remaining:
              $ref: '#/components/headers/X-Ratelimit-Remaining'
            X-Ratelimit-Reset:
              $ref: '#/components/headers/X-Ratelimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scan'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scans/{id}:
    get:
      summary: Retrieve a single scan entry
      operationId: retrieveScan
      parameters:
        - name: id
          in: path
          description: Scan ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          headers:
            X-Ratelimit-Limit:
              $ref: '#/components/headers/X-Ratelimit-Limit'
            X-Ratelimit-Remaining:
              $ref: '#/components/headers/X-Ratelimit-Remaining'
            X-Ratelimit-Reset:
              $ref: '#/components/headers/X-Ratelimit-Reset'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scan'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  headers:
    X-Ratelimit-Limit:
      schema:
        type: integer
    X-Ratelimit-Remaining:
      schema:
        type: integer
    X-Ratelimit-Reset:
      schema:
        type: integer

  schemas:
    Scan:
      required:
        - id
        - hosts
        - ports
        - description
        - type
        - status
      properties:
        id:
          type: string
        hosts:
          type: array
          items:
            type: string
        ports:
          type: array
          items:
            type: string
        type:
          type: string
        timeout:
          type: integer
        description:
          type: string
        status:
          type: string
          enum:
            - complete
            - scheduled
            - in_progress
            - failed

    NewScan:
      required:
        - hosts
        - ports
        - description
        - type
        - status
      properties:
        hosts:
          type: array
          items:
            type: string
        ports:
          type: array
          items:
            type: string
        timeout:
          type: integer
        type:
          type: string
          enum:
            - port_scan
            - service_discovery
            - service_discovery_default_scripts
        description:
          type: string

    Error:
      type: object
      required:
        - code
        - status
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        status:
          type: string
          description: Error message
        body:
          type: object

    Healthz:
      type: object
      required:
        - status
        - version
      properties:
        status:
          type: string
        version:
          type: string

  requestBodies:
    ScanBody:
      description: JSON of new Scan
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NewScan'

  parameters:
    PageParam:
      name: page
      in: query
      description: page number for pagination
      required: false
      schema:
        type: string
    PageSizeParam:
      name: page_size
      in: query
      description: page size for pagination
      required: false
      schema:
        type: string
    PageSortParam:
      name: sort
      in: query
      description: sort results
      required: false
      schema:
        type: string
